default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [admin.css, /sf/calendar/skins/aqua/theme.css, /sf/sf_admin/css/admin_main.css]

  javascripts:    [/sf/prototype/js/prototype.js]

  has_layout:     on
  layout:         layout
